# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# # pyatexec:alembic:{{ version }}:{{ rev_id }}
# # pyatexec:alembic:{{ version }}:{{ rev }}

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# installed by adding `python-dateutil` to requirements.txt.
# Value is ignored if the database connection does not have timezone
# support.
# Default: None
# timezone =

# max length of characters to apply to the
# "version path" of the file. If configured to the default value of 64,
# any version path that exceeds this length will be truncated to 64
# characters. For a value lower than 19, no versioning is performed.
# For example: version_path_terse=10 would produce file versions like
# 0001_2tbYbGcz.svg.
# Default: 64
# version_path_terse = 64

# When set to 'True', will not run a migration if the target database
# already contains the revision and any of its dependencies are indicated
# to be present. The implementation looks at
# `alembic_version` table for the target revision; if more than one head
# is present for an environment, this will filter for a revision that's
# already been applied. If the target database is SQLite and no
# `alembic_version` table is present, the revision is assumed to not be
# present, and the migration will run. Default: False
# skip_when_matches_against_existing = False

# Set to 'True' to emit DeprecationWarnings when the
# |migrations| or |versions| path does not exist for the target revision.
# Default: False
# warn_missing_paths = False

# sqlalchemy.url
# The SQLAlchemy connect string to use.
# Example: postgresql://user:password@localhost/dbname
# This can also take the form:
#   {{$SOME_ENV_VAR}}
# which will be replaced by the value of SOME_ENV_VAR from the environment
# at render time. If the variable is not set, an empty string will be
# substituted.
# No default value is set here.
sqlalchemy.url = postgresql://postgres:dev@localhost:5432/artha_dev

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s