"""Add auth fields to User model

Revision ID: 81970daaed6b
Revises: 995212365542
Create Date: 2026-08-27 14:59:01.499604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81970daaed6b'
down_revision: Union[str, None] = '995212365542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True), schema='financial')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), schema='financial')
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True), schema='financial')
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default=sa.text('\'user\'')), schema='financial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role', schema='financial')
    op.drop_column('users', 'last_login', schema='financial')
    op.drop_column('users', 'is_active', schema='financial')
    op.drop_column('users', 'hashed_password', schema='financial')
    # ### end Alembic commands ###