"""Add inflation_rate to goals table

Revision ID: 855df348c80f
Revises: 81970daaed6b
Create Date: 2026-08-28 19:04:23.209931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '855df348c80f'
down_revision: Union[str, None] = '81970daaed6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('inflation_rate', sa.Numeric(precision=5, scale=4), nullable=True), schema='financial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles', schema='financial')
    op.drop_table('liabilities', schema='financial')
    op.drop_table('insurance_policies', schema='financial')
    op.drop_table('income_sources', schema='financial')
    op.drop_table('goals', schema='financial')
    op.drop_table('financial_freedom_targets', schema='financial')
    op.drop_table('expenses', schema='financial')
    op.drop_table('assets', schema='financial')
    op.drop_table('users', schema='financial')
    op.drop_table('extracted_fields', schema='documents')
    op.drop_table('document_storage', schema='documents')
    # ### end Alembic commands ###
