"""Initial migration

Revision ID: 995212365542
Revises: 
Create Date: 2026-08-26 16:00:53.859529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '995212365542'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create schemas first
    op.execute('CREATE SCHEMA IF NOT EXISTS documents')
    op.execute('CREATE SCHEMA IF NOT EXISTS financial')
    op.execute('CREATE SCHEMA IF NOT EXISTS goals')
    op.execute('CREATE SCHEMA IF NOT EXISTS calculations')
    op.execute('CREATE SCHEMA IF NOT EXISTS audit')
    op.execute('CREATE SCHEMA IF NOT EXISTS lookup')

    op.create_table('document_storage',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('extraction_confidence', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('encryption_key_id', sa.UUID(), nullable=True),
    sa.Column('virus_scan_status', sa.String(length=20), nullable=True),
    sa.Column('virus_scan_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('document_id', 'id'),
    schema='documents'
    )
    op.create_table('extracted_fields',
    sa.Column('extracted_field_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_category', sa.String(length=20), nullable=False),
    sa.Column('extracted_value', sa.String(), nullable=False),
    sa.Column('parsed_value', sa.Integer(), nullable=True),
    sa.Column('parsed_date', sa.Date(), nullable=True),
    sa.Column('parsed_text', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('source_location', sa.String(length=100), nullable=True),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('verified_by_user', sa.Boolean(), nullable=False),
    sa.Column('user_corrected_value', sa.Integer(), nullable=True),
    sa.Column('user_corrected_date', sa.Date(), nullable=True),
    sa.Column('user_corrected_text', sa.String(), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('extracted_field_id', 'id'),
    schema='documents'
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=True),
    sa.Column('account_number_masked', sa.CHAR(length=4), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expected_return_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('liquidity', sa.String(length=10), nullable=True),
    sa.Column('is_joint_owned', sa.Boolean(), nullable=False),
    sa.Column('joint_owner_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nominee_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('asset_id', 'id'),
    schema='financial'
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('is_essential', sa.Boolean(), nullable=False),
    sa.Column('is_inflation_linked', sa.Boolean(), nullable=False),
    sa.Column('inflation_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('expense_id', 'id'),
    schema='financial'
    )
    op.create_table('financial_freedom_targets',
    sa.Column('ff_target_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_age', sa.Integer(), nullable=False),
    sa.Column('target_lifestyle_expenses', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('inflation_assumption', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('return_assumption', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('current_age', sa.Integer(), nullable=True),
    sa.Column('years_to_target', sa.Integer(), nullable=True),
    sa.Column('required_corpus', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_projected_corpus', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('freedom_gap', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('projected_freedom_age', sa.Integer(), nullable=True),
    sa.Column('assumptions_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('ff_target_id', 'id'),
    schema='financial'
    )
    op.create_table('goals',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.String(length=30), nullable=False),
    sa.Column('goal_name', sa.String(length=200), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_return', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('inflation_adjusted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('goal_id', 'id'),
    schema='financial'
    )
    op.create_table('income_sources',
    sa.Column('income_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('tax_withheld', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('growth_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('income_id', 'id'),
    schema='financial'
    )
    op.create_table('insurance_policies',
    sa.Column('insurance_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insurance_type', sa.String(length=30), nullable=False),
    sa.Column('policy_number_masked', sa.String(length=20), nullable=True),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('sum_assured', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('premium_frequency', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('beneficiaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nominee_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('riders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('insurance_id', 'id'),
    schema='financial'
    )
    op.create_table('liabilities',
    sa.Column('liability_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('liability_type', sa.String(length=30), nullable=False),
    sa.Column('lender_name', sa.String(length=200), nullable=False),
    sa.Column('account_number_masked', sa.CHAR(length=4), nullable=True),
    sa.Column('principal_outstanding', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('interest_type', sa.String(length=10), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_emis', sa.Integer(), nullable=False),
    sa.Column('emis_paid', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('prepayment_penalty_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_tax_deductible', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('liability_id', 'id'),
    schema='financial'
    )
    op.create_table('profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('profile_id', 'id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('user_id'),
    schema='financial'
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('dependents_count', sa.Integer(), nullable=False),
    sa.Column('residential_status', sa.String(length=20), nullable=False),
    sa.Column('pan_last_four', sa.CHAR(length=4), nullable=True),
    sa.Column('aadhaar_last_four', sa.CHAR(length=4), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('primary_occupation', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'id'),
    schema='financial'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='financial')
    op.drop_table('profiles', schema='financial')
    op.drop_table('liabilities', schema='financial')
    op.drop_table('insurance_policies', schema='financial')
    op.drop_table('income_sources', schema='financial')
    op.drop_table('goals', schema='financial')
    op.drop_table('financial_freedom_targets', schema='financial')
    op.drop_table('expenses', schema='financial')
    op.drop_table('assets', schema='financial')
    op.drop_table('extracted_fields', schema='documents')
    op.drop_table('document_storage', schema='documents')
    # Drop schemas if they exist and are empty
    op.execute('DROP SCHEMA IF EXISTS documents')
    op.execute('DROP SCHEMA IF EXISTS financial')
    op.execute('DROP SCHEMA IF EXISTS goals')
    op.execute('DROP SCHEMA IF EXISTS calculations')
    op.execute('DROP SCHEMA IF EXISTS audit')
    op.execute('DROP SCHEMA IF EXISTS lookup')
    # ### end Alembic commands ###
