"""Add advisor consent model and update user relationships

Revision ID: e20cee2b2dc8
Revises: 855df348c80f
Create Date: 2026-08-28 19:40:10.391183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e20cee2b2dc8'
down_revision: Union[str, None] = '855df348c80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unique constraint on users.user_id for foreign key reference
    op.create_unique_constraint('uq_users_user_id', 'users', ['user_id'], schema='financial')

    # Create advisor_consents table
    op.create_table('advisor_consents',
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('scope', sa.String(length=100), nullable=False, default='read_only'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['financial.users.user_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['financial.users.user_id'], ),
    sa.PrimaryKeyConstraint('consent_id', 'id'),
    schema='financial'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advisor_consents', schema='financial')
    op.drop_constraint('uq_users_user_id', 'users', type_='unique', schema='financial')
    # ### end Alembic commands ###